### ISSUE TITLE
setting cgroup config for procHooks process error

### ISSUE THREAD

**Issue by Emporea** [theia-ide/theia-apps#128]
I want to install the Theia IDE using docker on my VPS Ubuntu 18.04 (OpenVZ..).

`sudo docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next`

But it gives me the following error.

`Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write c 10:200 rwm to devices.allow: write /sys/fs/cgroup/devices/docker/ca751b45870250e8e6a22c3d749ace70748c4690ab362ed7e1cbbff449d5d869/devices.allow: operation not permitted\\\"\"": unknown.`

Is it possible to fix this? I not really into this but i read in several forums that OpenVZ hosting solution, like my provider does, often has problems with this sort of stuff. 

Btw this is the first time i am having such problems using docker, i am running Wordpress / Nextcloud etc. inside docker and its working perfectly fine.

**Comment by marcdumais-work** [comment]
Hummm... My guess is that your host provider has configured `/sys/fs/cgroup/...` to be read-only for security reasons, since this is a container environment and that all containers will share this resource from the host. 

This will limit what can be done in that environment. I am not sure what in Theia needs to modify one or more such "cgroup", but I assume it's not anything really Theia-specific, and that this limitation will also affect other docker images. 

In any case, I think this is beyond the intended scope of this repo.
