### ISSUE TITLE
Add Maven to java, full images

### ISSUE THREAD

**Issue by olberger** [theia-ide/theia-apps#131]
I think it may be interesting to add Maven to the Java image. But maybe other build systems could be more popular...

In any case, if anyone is interested, here are the proposed changed: https://github.com/olberger/theia-apps/commit/14d7da53ce12088c6f513d7ac5ea3a5f2710d691

Hope this helps,

**Comment by andreig** [comment]
I was also thinking about this, if you have done it already please add this to the -full also, not only the -java one. Full also contains "Java".

**Comment by marcdumais-work** [comment]
@olberger @andreig would you suggest a Maven version or version range that we should aim for?

**Comment by marcdumais-work** [comment]
@olberger would you care to submit your commit above as a PR, and also cover the [full](https://github.com/theia-ide/theia-apps/blob/master/theia-full-docker/Dockerfile) image, as suggested by @andreig ?  

I would suggest installing Maven as part of an existing `RUN apt get install [...]` command instead of adding an extra `RUN` command for it - it's good to keep the number of layers down.

**Comment by andreig** [comment]
On theia-full you can add it with "apt-get -y install openjdk-8-jdk", on theia-java you can add it with "apt-get install -y curl apt-transport-https". I just forked and I'm running my own image for now, keep in mind maven and gradle come with a lot of dependencies.
