### ISSUE TITLE
How to set up the debugger?

### ISSUE THREAD

**Issue by rohan-dave** [theia-ide/theia-apps#132]
I am currently using the docker-full docker image (https://github.com/theia-ide/theia-apps/tree/master/theia-full-docker), however the debugger is not working (nothing happens when you click on the menu option). Are there any external configurations needed for this to be set up?

**Comment by marcdumais-work** [comment]
Hi @rohan-dave ,

Any particular language you were looking to debug? 

I think the issue might just be that we have not updated the Theia packages list (latest.package.json / next.package.json) in a while for the full image, and ATM we do not include any debug-related extensions. 

e.g. to debug node.js applications, we would need these two: https://github.com/theia-ide/theia/blob/master/examples/browser/package.json#L17-L18

**Comment by rohan-dave** [comment]
That makes sense @marcdumais-work ,

I am looking to debug Python, Java, C++/C, Go. Is there support for these? I tried to use python-debug and debug-python, but that doesn't work.

**Comment by rohan-dave** [comment]
Thanks @marcdumais-work  ,

I am looking to debug Python, Java, C++/C, Go. Is there support for these? I tried to use python-debug and debug-python, but that doesn't work.

**Comment by rohan-dave** [comment]
any updates on this @marcdumais-work ?

**Comment by marcdumais-work** [comment]
Hi @rohan-dave from your list I think we only cover Java ATM (through `@theia/java-debug`). C/C++ is in very early stages of development and coming soon.

There is an ongoing activity to improve Theia's compatibility with VS Code extensions, and it seems likely that in the future we will be supporting Debug through this, rather than developing it from scratch, for many/most languages.
