### ISSUE TITLE
Issues with hover tooltip display on split screen.

### ISSUE THREAD

**Issue by GKJCJG** [theia-ide/theia-apps#316]
Using the Docker app with the recommended start command and Chrome 78.0.3904.87, I observed a couple of oddities in the display of hover tooltips.

If you hover over a symbol on the focused screen and the tooltip overflows into the other screen, part of the barrier between the screens is visible over the tooltip.

![bar-over-tooltip](https://user-images.githubusercontent.com/43424668/75933797-70b43e80-5e40-11ea-8afa-385892b2eff9.png)

If you over over a symbol on the non-focused screen and the tooltip overflows onto the focused screen it is occluded. This may be desirable (it is coming from the unfocused screen, after all), but if that's the intent, perhaps the tooltip shouldn't be shown at all for non-focused content.

![half-occluded-tooltip](https://user-images.githubusercontent.com/43424668/75933818-7dd12d80-5e40-11ea-8529-fd49a83ded60.png)

**Comment by vince-fugnitto** [comment]
@GKJCJG thank you for the issue! 
I'll be closing the issue here since it should be reported to the upstream [theia](https://github.com/eclipse-theia/theia) repository.

It looks like the issue has been previously reported:
- https://github.com/eclipse-theia/theia/issues/6272
- https://github.com/eclipse-theia/theia/issues/2417
