### ISSUE TITLE
[rust] Rust image runs as root.

### ISSUE THREAD

**Issue by jchv** [theia-ide/theia-apps#335]
theia-full does not seem to run as root, fixed apparently in #56. So it seems likely that it should be possible to get theia-rust to run as a normal user.

**Comment by jchv** [comment]
Ah, I am at least partially mistaken, as it appears that in the case of the Rust image, there is some custom scaffolding going on that lets you use a user optionally. It is documented, though I am still a bit confused. Is it expected that the images may vary quite a bit in operation?

**Comment by vince-fugnitto** [comment]
> Ah, I am at least partially mistaken, as it appears that in the case of the Rust image, there is some custom scaffolding going on that lets you use a user optionally. It is documented, though I am still a bit confused. Is it expected that the images may vary quite a bit in operation?

You make take a look at the [rust readme](https://github.com/theia-ide/theia-apps/blob/master/theia-rust-docker/README.md) and more specifically the section [how it works](https://github.com/theia-ide/theia-apps/blob/master/theia-rust-docker/README.md#how-does-it-work) where it describes setting up the user.

**Comment by marcdumais-work** [comment]
> Is it expected that the images may vary quite a bit in operation?

Indeed, there is a fair amount of variation between the images. The Rust image might be the one that stands-out the most, having quite a bit of helper scripts around it. The biggest problem wioth this image is that it has not being building consistently for about 6 months now: https://github.com/theia-ide/theia-apps/issues/253 , apparently because of a [weird toolchain issue](https://travis-ci.org/github/theia-ide/theia-apps/jobs/671458302#L1769-L1792). It did build for a little while a couple of months ago.
