### ISSUE TITLE
Feature Request: Node Version Customization

### ISSUE THREAD

**Issue by XenfoMC** [theia-ide/theia-apps#358]
I would like to change my Node.js version to 12.0.0 but apparently it would be pretty complicated. I need to use Node.js 12.0.0 because the main library I work with does not support Theia's Node.js version. If you do something where you can pick your version it would be appreciated.

**Comment by vince-fugnitto** [comment]
@marcdumais-work could we include `nvm` in the images so that users can benefit from switching node versions easily?

**Comment by marcdumais-work** [comment]
> @marcdumais-work could we include `nvm` in the images so that users can benefit from switching node versions easily?

Maybe but using `nvm` in docker can be a little tricky, even without considering the part about having Theia use a different node version vs other processes. I think the `rust` image uses `nvm` and could be used as example if we'd like to go forward with this idea. IIRC for `nvm` to work in docker, one can't directly start the Theia application from the docker entry-point, but must instead use a script that sources or defines the `nvm` config so it's active, and then starts the Theia application once the correct node is set for it. 

I did a quick test and when in a terminal I set a non-default nvm node version, any other terminal/process I spawn from it continue to use the value I set instead of Default, so it may be tricky to use another node version for any process that is spawned by Theia. I guess we would need to prototype and try things to see if possible.

**Comment by XenfoMC** [comment]
Ok. Thanks for looking into it. :D

**Comment by marcdumais-work** [comment]
@XenfoMC FYI we are considering switching to node 12 for Theia anyway sometime soon. So while there may be a need to offer this type of flexibility generally, your personal use-case should work OOTB after that update.

**Comment by XenfoMC** [comment]
Ooh. That's great.

**Comment by vince-fugnitto** [comment]
The applications have been updated to use `node 12` now that the framework supports it and `node 10` is dropped.
- https://github.com/theia-ide/theia-apps/pull/391
