### ISSUE TITLE
Git Clone from gitlab and gogs does not work

### ISSUE THREAD

**Issue by erdalkaraca** [theia-ide/theia-apps#474]
#### Bug Description:

Git cloning from a gitlab or gogs repository does not work, i.e. I can see an empty (bare) git repo created, but the contents are not fetched - I tried with both public and private repos.
Cloning from a github repo works as expected.

#### Steps to Reproduce:

Call Git Clone command and enter a repo URL from either gitlab or gogs.

#### Additional Information

Using docker image theia-full:latest.

**Comment by vince-fugnitto** [comment]
@erdalkaraca I did the following and it worked for me:

1. `docker pull theiaide/theia-full:latest`
2. `docker run --init -p 3000:3000 theiaide/theia-full:latest`
3. I then started the app, and performed a `git clone` using `https` from a `public` gitlab repository (ex: [hello_world](https://gitlab.com/doody2009/hello_world))

**Comment by erdalkaraca** [comment]
@vince-fugnitto That is strange, that repo also works for me.

Can you try the following repo:

https://gitlab.uni-oldenburg.de/fare4678/ml-neurophysio.git

**Comment by vince-fugnitto** [comment]
> Can you try the following repo

It correctly asks me for credentials (I do not have `ssh` keys set up or anything):

<img width="848" alt="Screen Shot 2021-04-14 at 4 55 36 PM" src="https://user-images.githubusercontent.com/40359487/114778059-60a8a700-9d42-11eb-8ec3-ab7d0c775f3a.png">

**Comment by erdalkaraca** [comment]
Thanks for the screenshot. Now, I see you are cloning in terminal. I was using F1>Git Clone command which does not ask for credentials.
In terminal I can also clone the repo.

**Comment by vince-fugnitto** [comment]
> Thanks for the screenshot. Now, I see you are cloning in terminal. I was using F1>Git Clone command which does not ask for credentials.

I see, thank you for the clarification (I use the terminal and it's a habit).

There are a couple of options for your own application:
- move towards using `vscode-builtin-git` to provide git features instead of `@theia/git`: https://open-vsx.org/api/vscode/git/1.49.3/file/vscode.git-1.49.3.vsix - this is the long term solution, the `theia-apps` repos have not been migrated to use the builtin over the custom implementation.
- using the terminal for the time being.

I'll open a follow-up issue in the framework about possibly improving `@theia/git` to behave similarly to the builtin.
