### ISSUE TITLE
New Language Support: Haskell

### ISSUE THREAD

**Issue by lapplislazuli** [theia-ide/theia-apps#478]
Hi there 👋 , 

I would currently like to use Theia with Haskell. 
Is this something you accept PR's for? 
I'd basically reproduce [the cpp image](https://github.com/theia-ide/theia-apps/blob/master/theia-cpp-docker/Dockerfile) just with the haskell compiler and tools in the later parts. 

Is there anything else (except the contribution guidelines) that I should be aware of?

**Comment by vince-fugnitto** [comment]
@lapplislazuli thank you for your interest in the project :+1: 

We have been moving towards having less images overall (https://github.com/theia-ide/theia-apps/issues/402) since it increases maintenance and the images are solely for example purposes (and also to test CI against the [main repository](https://github.com/eclipse-theia/theia)). Given that the `haskell` image is likely not so complicated or different than other images I'm not sure it adds much value at this time to include it in the repository as an example for others. You can however inspire yourself from other images to develop and use it yourself :smiley: 

cc @marcdumais-work

**Comment by vince-fugnitto** [comment]
Please see also:
- https://github.com/theia-ide/theia-apps/pull/177#issuecomment-788900648
- https://github.com/theia-ide/theia-apps/pull/177#issuecomment-789028656

Perhaps including it in `theia-full` would be an alternative to a completely new image.

**Comment by lapplislazuli** [comment]
Good Morning, 

Thanks for the quick responses 😄 
I first wanted to ask before I start a PR out of the blue. Keeping your maintenance low is something I can understand. 

I think I'll first do a Theia-Haskell similar to the CPP image (privately), and then make a PR for the Theia Full 👍
