### ISSUE TITLE
[eslint] add 'eslint' support for ts, js images

### ISSUE THREAD

**Issue by bdefore** [theia-ide/theia-apps#65]
Would be very helpful for JavaScript development to have inline eslint warnings in Theia, along the lines of what we currently have for Typescript.

FWIW, this is something currently supported by https://codesandbox.io/

**Comment by akosyakov** [comment]
We should make use of eslint LS: https://github.com/Microsoft/vscode-eslint/tree/master/server

**Comment by sr229** [comment]
Not sure if Theia's LS is VSCode compatible, we might need to rewrite `vscode-eslint` for Theia

**Comment by marcdumais-work** [comment]
update: since last fall Theia has increasingly gained compatibility with VS Code extensions (run as Theia plugins). I do not remember if `eslint` was tested, but there's a fair chance it would work out-of-the-box.

**Comment by realies** [comment]
Can ESLint be ran in the Theia docker container somehow? Setting the plugin path as an environment variable and placing the vsix in the folder does not seem to work.

**Comment by marcdumais-work** [comment]
@realies yes, I just confirmed that it works. For convenience I started with an image that already has plugin support: theia-go, and added dependencies to support TypeScript (@theia/typescript, typescript), installed eslint globally and added the .vsix file in the plugins folder. 

See this for reference: https://github.com/marcdumais-work/theia-apps/commit/ebf1ef62dd92fa8c9b54a6a2f7639d5f8e6aecd6

I tested using this repo: https://github.com/trevordmiller/example-eslint and got eslint diagnostics and the eslint commands are available from the command palette.

![image](https://user-images.githubusercontent.com/25749063/62213111-35183a00-b370-11e9-8cdc-45a066e536b3.png)

**Comment by vince-fugnitto** [comment]
> @realies yes, I just confirmed that it works. For convenience I started with an image that already has plugin support: theia-go, and added dependencies to support TypeScript (@theia/typescript, typescript), installed eslint globally and added the .vsix file in the plugins folder.
> 
> See this for reference: [marcdumais-work@ebf1ef6](https://github.com/marcdumais-work/theia-apps/commit/ebf1ef62dd92fa8c9b54a6a2f7639d5f8e6aecd6)
> 
> I tested using this repo: https://github.com/trevordmiller/example-eslint and got eslint diagnostics and the eslint commands are available from the command palette.
> 
> ![image](https://user-images.githubusercontent.com/25749063/62213111-35183a00-b370-11e9-8cdc-45a066e536b3.png)

@marcdumais-work should we update the `theia-docker` image to include plugins such as `eslint`?

**Comment by marcdumais-work** [comment]
> should we update the `theia-docker` image to include plugins such as `eslint`?

Could be interesting but low priority.

**Comment by brandonkal** [comment]
Please remove the stale bot. It is such a bad experience and drives contributors away. This still appears actionable.

**Comment by vince-fugnitto** [comment]
@bdefore thanks for your concern! In general, the `stalebot` is a tool which allows the project to keep the number of relevant issues at a manageable level as well as inform committers that actions may still be required. 

In the case of the addition of the `eslint` plugin in images that may benefit from it, it is in fact an interesting issue but not of the highest priority at the moment. However, nothing prevents contributors such as yourself to submit pull requests in order to land the feature. You may see https://github.com/marcdumais-work/theia-apps/commit/ebf1ef62dd92fa8c9b54a6a2f7639d5f8e6aecd6 as an example of how to do so.

I will also update the issue labels in order to tell `stalebot` to ignore the issue.
We can also discuss as a project if `stalebot` should in fact be removed.
