### ISSUE TITLE
Support of Python3

### ISSUE THREAD

**Issue by dclong** [theia-ide/theia-apps#74]
It's great to see the Docker for Python added. I've tried it and it works well. However, it is for Python2 only currently. Can we add support of Python3?

**Comment by jgroom33** [comment]
go for it: https://github.com/theia-ide/theia-apps/blob/master/theia-python-docker/Dockerfile#L4

**Comment by dclong** [comment]
@jgroom33 

I tried to replace Python 2 with Python 3 in the Dockerfile, but it doesn't work as expected. Python 3 syntax is not recognized. There were an error message on startup (cannot remember exactly, will report later).

**Comment by marcdumais-work** [comment]
@dclong Do I understand correctly that the idea situation, for Python, would be to support both version 2.x and 3.x in the same image(s)? It seems this might be tricky, since I think we would need to know which version of the LS we need to start, when opening a .py file. 

Maybe we could have a preference for the name of the python executable Theia will attempt to use as a LS.

**Comment by simark** [comment]
It is typical in Python to work with virtual environments, which are self-contained Python installations that you create to work on a particular project.  It's useful (and sometimes necessary) even if you use the same version of Python with multiple projects, since you might need different packages for each project.  So in a way, it also acts kind of as the node_modules directory in node projects, except it's usually created out of tree.  So let's say I work on two unrelated projects, one which uses Python 2 and the other Python 3, I would create two virtualenvs:

```
$ virtualenv -p /usr/bin/python2 python2-env
$ virtualenv -p /usr/bin/python3 python3-env
```

Then, you source the `activate` file in the virtual environment you want to use to have access to it in that shell.

Now, in Theia, I'm not sure what would the most convenient.  The few times I tried IDEs for Python (mostly PyDev in Eclipse), it allowed you to list your existing virtualenvs, and let you select which one to use.  We can probably do the same.  In some way, it reminds me a bit of C/C++ build configurations, since you can have multiple "builds" with a single source.

Because each user creates their virtualenv wherever they want, I guess that the list of  virtualenvs would most likely reside in the user's home config (since the workspace config is expected to be checked in).  But I can imagine a team where everybody uses the same paths, so they would want to put the list in the workspace config.  In that case, we probably want the list of virtualenvs in the workspace config to be appended to the list from the user's config, not overwrite/shadow it.

**Comment by dclong** [comment]
I know this might arouses debates. If it's hard to support both Python 2 and Python 3 in Theia, then we should support Python 3 rather than Python 2 in Theia. Official support of Python 2 will end in a couple of years anyway.

**Comment by jgroom33** [comment]
Or just have two images

**Comment by marcdumais-work** [comment]
> Or just have two images

+1. I was just thinking the same thing. Maybe we could have a Dockerfile ARG, that can be set one the command-line when building the image, that controls which version of the Python packages gets installed ,in a given image. When releasing, we might build, eventually test, then and publish two versions of the image, each dedicated to a specific Python version. e.g.: 
- theia-python2
- theia-python3

**Comment by svenefftinge** [comment]
I don't think there are users relying on python2 but Theia needs it. 

https://github.com/nodejs/node-gyp#on-unix

So we don't need a python2 docker, but one that has both, defaults to python3 and make node use python2:

`npm config set python /path/to/executable/python2.7`

**Comment by marcdumais-work** [comment]
Maybe we could refactor the image so it's built in two steps, like [theia-docker](https://github.com/theia-ide/theia-apps/blob/master/theia-docker/Dockerfile). Then the Theia build dependencies can be part of the first part, and runtime dependencies the second.

**Comment by marcdumais-work** [comment]
Theia items related to this issue: 
- [Python virtual env support](https://github.com/theia-ide/theia/issues/2973)
- [Related discussion](https://github.com/theia-ide/theia/commit/4ba4e6532b65f51ae1054fb1297498bec864498d#r30632208)

**Comment by jpambrun** [comment]
For those interested, this seems to work for me:

``` Dockerfile
FROM node:8-stretch  as builder
RUN apt-get update \
    && apt-get install -y python \ 
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

WORKDIR /home/thei
ADD package.json ./package.json
RUN yarn --cache-folder ./ycache && rm -rf ./ycache
RUN yarn theia build

FROM node:8-stretch
WORKDIR /home/thei
COPY --from=builder /home/thei .

RUN apt-get update \
    && apt-get install -y python3 python3-dev python3-pip \ 
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN rm /usr/bin/python && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip
    
RUN pip install \
    python-language-server \
    flake8 \
    autopep8 \
    futures \
    configparser

EXPOSE 3000
ENV SHELL /bin/bash
ENTRYPOINT [ "yarn", "theia", "start", "/src", "--hostname=0.0.0.0" ]
```

**Comment by sr229** [comment]
I'll open a PR to do this

**Comment by dclong** [comment]
It seems to me that Gitpod (theia-based) supports Python3.

**Comment by Leletir** [comment]
@jpambrun we could also 
```dockerfile
RUN  update-alternatives --install /usr/bin/python python /usr/bin/python3 1
```
instead of deleting /usr/bin/python

and 
```dockerfile
RUN pip3 install \
    python-language-server \
    flake8 \
    autopep8 \
    futures \
    configparser
```

Because some os have stong dependencies with python 2 (rhel and yum for example)

Full dockerfile:
```dockerfile
FROM node:8-stretch  as builder
RUN apt-get update \
    && apt-get install -y python \ 
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

WORKDIR /home/thei
ADD package.json ./package.json
RUN yarn --cache-folder ./ycache && rm -rf ./ycache
RUN yarn theia build

FROM node:8-stretch
WORKDIR /home/thei
COPY --from=builder /home/thei .

RUN apt-get update \
    && apt-get install -y python3 python3-dev python3-pip \ 
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN  update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    #ln -s /usr/bin/python3 /usr/bin/python && \
    #ln -s /usr/bin/pip3 /usr/bin/pip
    
RUN pip3 install \
    python-language-server \
    flake8 \
    autopep8 \
    futures \
    configparser \
    rope \
    pydocstyle \
    yapf

EXPOSE 3000
ENV SHELL /bin/bash
ENTRYPOINT [ "yarn", "theia", "start", "/src", "--hostname=0.0.0.0" ]
```

What do you think ?

**Comment by sr229** [comment]
I think we can use the Python 3.6 Docker image and just install node.js, that way we have a standard Theia with upstream Python

**Comment by jpambrun** [comment]
I am not using theia these days so I don't have a strong opinion. I just posted what worked for me hoping it could help others.

**Comment by dclong** [comment]
Can we keep this issue alive?
